version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/javascript"
    schedule:
      interval: "daily"
    groups:
      cdk-dependencies:
        patterns:
          - "aws-cdk"
          - "aws-cdk-lib"
    allow:
      - dependency-name: "aws-cdk"
      - dependency-name: "aws-cdk-lib"