version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/javascript"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "aws-cdk"
      - dependency-name: "aws-cdk-lib"